### ISSUE TITLE
Missing Symbol / Footprint

### ISSUE THREAD

**Issue by hmaerki** [CIRCUITSTATE/Mitayi-Pico-RP2040#1]
Hi Vishnu

I had a look at ths PCB and I like it a lot!

There is a symbol of U3 missing `CIRCUITSTATE-Microcontrollers:RP2040`
These footprints are missing:
CIRCUITSTATE-QFN:RP2040-QFN-56
JP5 (CIRCUITSTATE_Jumper_SMD:Solder-Jumper_2P_Open_0402
SW2 (CIRCUITSTATE_Switch_SMD:CK_SW_SPST_UK-B0273-SP25YG
CIRCUITSTATE-Graphics:Circuitstate-Logomark-27x3.8mm

Could you add this symbol/footprint please.

Thank you
    Hans

Keep going with you excellent work!

**Comment by vishnumaiea** [comment]
Hi Hans. Glad you like it. The footprints you have mentioned are custom footprints I designed for the board. They were saved to local libraries in my system, not to the project folder. So you won't find them in the project folder. But, all footprints must be cached on the design files, even if they are not in your system. You can open a footprint in the footprint editor and "Save As" it somewhere else if you plan to reuse them on a different project.

Does KiCad throw any errors while trying to load the files on your side? If yes, could you please share a screenshot? I hope you are using the latest KiCad release.

Please let me know if this helps.

**Comment by hmaerki** [comment]
Hi Vishnu

Thanks for your quick response!

I use

> Application: KiCad Schematic Editor x86_64 on x86_64
> Version: 7.0.6-7.0.6~ubuntu23.04.1, release build


You proposed
>  You can open a footprint in the footprint editor and "Save As"

I did:
Schema Editor -> U3 -> Properties -> 
![image](https://github.com/CIRCUITSTATE/Mitayi-Pico-RP2040/assets/8708771/c61d735c-ffda-4dd3-b717-cbde6fa48998)

![image](https://github.com/CIRCUITSTATE/Mitayi-Pico-RP2040/assets/8708771/d12f7ad0-2f56-4f69-98b3-cf6232c2e8f1)

So I guess that footprint is not cached.

These are all the missinig footprints/symbols:

```
Error: Update symbol U3 from 'CIRCUITSTATE-Microcontrollers:RP2040' to 'CIRCUITSTATE-Microcontrollers:RP2040': *** symbol not found ***

Error: Updated footprint J4 (CIRCUITSTATE-Connector-Pin-Headers:PinHeader_1x20_2H_P2.54mm_Vertical): *** library footprint not found ***
Error: Updated footprint G*** (CIRCUITSTATE-Graphics:Circuitstate-Logomark-27x3.8mm): *** library footprint not found ***
Error: Updated footprint JP6 (CIRCUITSTATE_Jumper_SMD:Solder-Jumper_3P_Open_0402): *** library footprint not found ***
Error: Updated footprint SW2 (CIRCUITSTATE_Switch_SMD:CK_SW_SPST_UK-B0273-SP25Y): *** library footprint not found ***
Error: Updated footprint J3 (CIRCUITSTATE-Connector-Pin-Headers:PinHeader_1x20_2H_P2.54mm_Vertical): *** library footprint not found ***
Error: Updated footprint SW1 (CIRCUITSTATE_Switch_SMD:CK_SW_SPST_UK-B0273-SP25Y): *** library footprint not found ***
Error: Updated footprint JP4 (CIRCUITSTATE_Jumper_SMD:Solder-Jumper_2P_Open_0402): *** library footprint not found ***
Error: Updated footprint J2 (CIRCUITSTATE_Connector_USB:Korean-Hroparts-Elec_TYPE-C-31-M-12): *** library footprint not found ***
Error: Updated footprint JP1 (CIRCUITSTATE_Jumper_SMD:Solder-Jumper_2P_Open_0402): *** library footprint not found ***
Error: Updated footprint U3 (CIRCUITSTATE-QFN:RP2040-QFN-56): *** library footprint not found ***
Error: Updated footprint JP5 (CIRCUITSTATE_Jumper_SMD:Solder-Jumper_2P_Open_0402): *** library footprint not found ***
```

**Comment by vishnumaiea** [comment]
Footprints are cached on the PCB files only. The schematic files will just have the library path as a string in the schematic field, which if you tried to locate will end in a "not found" error. But KiCad is smart enough to understand that, despite the footprint path provided in the schematic files missing on your system, you have valid footprints assigned in the PCB design file.

If you want to assign the footprints in the schematic file without errors, you must save the footprints from the PCB file to a custom library of yours.

Even better, the PCB editor has an export option called "Footprints to New Library" which will save all the footprints in the PCB file to a custom new library. Simply save it to your system and reassign the missing ones. It is better to save the new library inside your project folder so that KiCad will replace the absolute path name with a relative one.

**Comment by hmaerki** [comment]
Thanks a lot - you are a hero!

I exported "Footprints to New Library". This worked great.

The issue is resolved.
